stages:          
  - build
  - deploy
  - status

build:
  image: maven:3.9.4-eclipse-temurin-17-alpine
  stage: build
  script:
    - mvn clean package
  artifacts:
    name: "hrms-jar-artifact"
    paths:
      - target/*.jar
#copied till here
deploy:
  image: alpine
  stage: deploy
  dependencies:
    - "build"
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - cd target
    - mv NeoLedger-0.0.1-SNAPSHOT.jar HRMS-0.0.1-SNAPSHOT.jar
    - scp -o StrictHostKeyChecking=no HRMS-0.0.1-SNAPSHOT.jar $SERVER_USER@$SERVER_IP:/home/staginguser/java-application/jar-files
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "bash /home/staginguser/java-application/jar-files/deploy-script.sh hrms"

deploy-status:
  image: alpine
  stage: status
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "tail -1 /home/staginguser/java-application/jar-files/deployment-history.txt"
